version: '3.1'

services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: databasephp
    expose:
      - 5432/tcp
    ports:
      - "127.0.0.1:5438:5432/tcp"
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  pgdata: